<a href="https://colab.research.google.com/github/SeokcheonMoon/study_AIs/blob/main/docs/MLs/Regression/01_linearRegression_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Regression(회귀예측)
- 데이터
- 모델
- 평가

### 데이터

In [ ]:
from sklearn import datasets
diabetes_X, diabetes_Y = datasets.load_diabetes(return_X_y=True)
diabetes_X, diabetes_Y

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
   

In [ ]:
type(diabetes_X), type(diabetes_Y)

(numpy.ndarray, numpy.ndarray)

In [ ]:
diabetes_X.shape , diabetes_Y.shape

((442, 10), (442,))

### 모델

In [ ]:
from sklearn import linear_model
linear_regression = linear_model.LinearRegression()                   # 학습 장소 선택
linear_regression

LinearRegression()

In [ ]:
linear_regression.fit(diabetes_X,diabetes_Y)                        # 학습 진행

LinearRegression()

### 평가

In [ ]:
diabetes_X[:2],diabetes_Y[:2]

(array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
         -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
         -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405]]),
 array([151.,  75.]))

In [ ]:
linear_regression.predict(diabetes_X[:2])                   # 똑같지 않지만 유사함.

array([206.11667725,  68.07103297])