<a href="https://colab.research.google.com/github/SeokcheonMoon/study_AIs/blob/main/docs/MLs/classfications/01_LogisticRegression_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터


In [2]:
from sklearn.datasets import load_iris

In [5]:
iris_X , iris_Y = load_iris(return_X_y=True)

In [7]:
type(iris_X),type(iris_Y), iris_X.shape, iris_Y.shape

(numpy.ndarray, numpy.ndarray, (150, 4), (150,))

In [9]:
iris_X[:3], iris_X[-3:]

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2]]),
 array([[6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]))

In [10]:
iris_Y[:3],iris_Y[-3:]

(array([0, 0, 0]), array([2, 2, 2]))

## 모델 선택과 학습

In [13]:
from sklearn import linear_model

In [15]:
logisticRegression = linear_model.LogisticRegression()
logisticRegression

LogisticRegression()

In [16]:
logisticRegression.fit(iris_X,iris_Y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

### 평가

In [18]:
logisticRegression.predict(iris_X[:3])

array([0, 0, 0])

In [21]:
logisticRegression.predict(iris_X[-3:])

array([2, 2, 2])

### 학습 방식 확인

In [26]:
logisticRegression.predict_proba(iris_X[:1])

array([[9.81799409e-01, 1.82005762e-02, 1.43509289e-08]])

In [25]:
logisticRegression.predict(iris_X[:1])                    # 위 코드에서 셋 중 가장 확률적으로 숫자가 큰 값의 인덱스를 가져옴.  index0이 가장 숫자가 크기 때문에 array[0]이 나온거임

array([0])